import {
  Code2,
  Database,
  Layout,
  Terminal,
  Server,
  Globe
} from "lucide-react";

export const PORTFOLIO_DATA = {
  personalInfo: {
    name: "Alfathalif Dewa Listyoka",
    role: "Software Engineer",
    tagline: "Kukira nge-bug, ternyata Backburner",
    bio: "I am a passionate software engineer focused on building robust, scalable, and visually appealing web applications. I enjoy tackling complex problems, learning new technologies, and continuously improving my craft.",
    avatarUrl: "/images/ProfilePicLogo.png",
    contactEmail: "alfathalifdewa02@gmail.com",
  },

  tools: [
    { name: "VSCode", icon: "/images/tools/vscode.svg", description: "Code Editor" },
    { name: "JavaScript", icon: "/images/tools/javascript.svg", description: "Programming Language" },
    { name: "ReactJS", icon: "/images/tools/reactjs.svg", description: "UI Library" },
    { name: "Node.js", icon: "/images/tools/nodejs.svg", description: "Runtime Environment" },
    { name: "Express.js", icon: "/images/tools/expressjs.svg", description: "Web Framework" },
    { name: "PHP", icon: "/images/tools/php.svg", description: "Server-side Language" },
    { name: "Laravel", icon: "/images/tools/laravel.svg", description: "PHP Framework" },
    { name: "MySQL", icon: "/images/tools/mysql.svg", description: "Database" },
    { name: "MongoDB", icon: "/images/tools/mongodb.svg", description: "NoSQL Database" },
    { name: "Java", icon: "/images/tools/java.svg", description: "Programming Language" },
    { name: "Python", icon: "/images/tools/python.svg", description: "Programming Language" },
    { name: "XAMPP", icon: "/images/tools/xampp.svg", description: "Local Web Server" },
    { name: "GitHub", icon: "/images/tools/github.svg", description: "Version Control" },
    { name: "Netlify", icon: "/images/tools/netlify.svg", description: "Hosting & Deployment" },
    { name: "Canva", icon: "/images/tools/canva.svg", description: "Graphic Design" },
    { name: "CapCut", icon: "/images/tools/capcut.svg", description: "Video Editing" },
  ],

  community: [
    {
      platform: "GitHub",
      username: "@alfathalifdewa",
      description: "Open source projects, code experiments & contributions.",
      url: "https://github.com/alfathalifdewa",
      icon: "SiGithub",
      color: "#333",
    },
    {
      platform: "LinkedIn",
      username: "Alfathalif Dewa",
      description: "Professional network, career updates & insights.",
      url: "https://www.linkedin.com/in/alfathalif-dewa/",
      icon: "SiLinkedin",
      color: "#0A66C2",
    },
    {
      platform: "Instagram",
      username: "@alfathalifdewa",
      description: "Behind the scenes, life & creative content.",
      url: "https://www.instagram.com/alfathalifdewa/",
      icon: "SiInstagram",
      color: "#E1306C",
    },
    {
      platform: "TikTok",
      username: "@needpancake",
      description: "Tech tips, coding videos & trending content.",
      url: "https://www.tiktok.com/@needpancake",
      icon: "SiTiktok",
      color: "#010101",
    },
    {
      platform: "X (Twitter)",
      username: "@needpancake",
      description: "Thoughts on tech, dev life & random stuff.",
      url: "https://x.com/needpancake",
      icon: "SiX",
      color: "#000",
    },
  ],

  brands: [
    { name: "Kementerian Kebudayaan", logo: "/images/brand/kemenbud.png" },
    { name: "Indonesiana TV", logo: "/images/brand/indonesianatv.png" },
    { name: "Kampus Merdeka", logo: "/images/brand/kampusmerdeka.png" },
    { name: "MSIB", logo: "/images/brand/msib.png" },
    { name: "Educa Studio", logo: "/images/brand/Educastudio.png" },
    { name: "Gamelab Indonesia", logo: "/images/brand/gamelab.png" },
    { name: "Virus Digital Indonesia", logo: "/images/brand/virusdigitalindonesia.png" },
  ],

  skills: {
    categories: [
      {
        title: "Frontend",
        icon: Layout,
        items: ["React", "Next.js", "TypeScript", "Tailwind CSS", "HTML/CSS"],
      },
      {
        title: "Backend",
        icon: Server,
        items: ["Node.js", "Express", "Python", "REST APIs", ".NET"],
      },
      {
        title: "Database",
        icon: Database,
        items: ["PostgreSQL", "MongoDB", "MySQL"],
      },
      {
        title: "Tools",
        icon: Terminal,
        items: ["Git", "Docker", "AWS", "Canva", "Ms. Office"],
      },
    ],
  },

  projects: [
    {
      id: 1,
      title: "E-Commerce Platform",
      description: "A full-stack e-commerce solution with modern UI, secure payment integration, and a comprehensive admin dashboard.",
      techStack: ["Next.js", "TypeScript", "Tailwind CSS", "PostgreSQL"],
      githubUrl: "https://github.com/alfathalifdewa",
      liveUrl: "https://example.com",
      image: "/images/project/VEGESALE.svg",
    },
    {
      id: 2,
      title: "Task Management App",
      description: "A collaborative task management tool featuring real-time updates, kanban boards, and team workspaces.",
      techStack: ["React", "Node.js", "Socket.io", "MongoDB"],
      githubUrl: "https://github.com/alfathalifdewa",
      liveUrl: "https://example.com",
      image: "/images/project/SEBLAKDUNAX.svg",
    },
    {
      id: 3,
      title: "AI Chat Interface",
      description: "A modern chat interface integrated with OpenAI API, featuring markdown support and conversation history.",
      techStack: ["React", "Tailwind CSS", "OpenAI API"],
      githubUrl: "https://github.com/alfathalifdewa",
      liveUrl: "https://example.com",
      image: "/images/project/MIEX.svg",
    },
    {
      id: 4,
      title: "Data Dashboard",
      description: "An interactive analytics dashboard visualizing key business metrics with charts and real-time data feeds.",
      techStack: ["Python", "FastAPI", "React", "Chart.js"],
      githubUrl: "https://github.com/alfathalifdewa",
      liveUrl: "https://example.com",
      image: "/images/project-placeholder.svg",
    },
    {
      id: 5,
      title: "REST API Boilerplate",
      description: "Production-ready Node.js REST API with authentication, rate limiting, logging, and Docker support.",
      techStack: ["Node.js", "Express", "JWT", "Docker", "PostgreSQL"],
      githubUrl: "https://github.com/alfathalifdewa",
      liveUrl: "https://example.com",
      image: "/images/project-placeholder.svg",
    },
    {
      id: 6,
      title: "Portfolio CMS",
      description: "A headless CMS-powered portfolio system with live preview, markdown editor, and one-click deploy.",
      techStack: ["Next.js", "Sanity.io", "TypeScript", "Vercel"],
      githubUrl: "https://github.com/alfathalifdewa",
      liveUrl: "https://example.com",
      image: "/images/project/CMS.svg",
    },
  ],

  experience: [
    {
      id: 1,
      company: "Ministry of Culture of Republic Indonesia",
      role: "Operational Services Officer",
      duration: "2025 - 2026",
      achievements: [
        "Handle podcast production process for the Directorate of Film, Music, and Animation.",
        "Create short films and promotional videos for events such as Festival Film Indonesia (FFI) and Asia Pacific Screen Awards (APSA).",
        "Manage and document film synopses, broadcast data, and staff administrative data.",
      ],
    },
    {
      id: 2,
      company: "PT Educa Sisfomedia Indonesia",
      role: "Web Backend Developer",
      duration: "Feb 2023 - Agu 2023",
      achievements: [
        "Developed and maintained backend systems using Node.js and Express.js.",
        "Designed and implemented RESTful APIs for client applications.",
        "Integrated third-party services and payment gateways.",
      ],
    },
    {
      id: 3,
      company: "CV Virus Digital Indonesia",
      role: "Web Developer",
      duration: "Jan 2020 - Mar 2020",
      achievements: [
        "Maintain and optimized website performance.",
        "Added new features to improve user experience.",
        "Integrated third-party services and payment gateways.",
      ],
    },
  ],

  education: [
    {
      id: 1,
      institution: "Universitas Indraprasta PGRI",
      degree: "Bachelor of Informatics Engineering",
      duration: "2021 - 2025",
    },
    {
      id: 2,
      institution: "SMKN 1 Cibinong",
      degree: "Software Engineering",
      duration: "2018 - 2021",
    },
  ],

  caseStudies: [
    {
      id: 1,
      title: "Content Metadata Management & Validation",
      category: "Content Library",
      datasetInfo: "4K+ rows • Excel • Kumulate",
      problem: "Digital content metadata and production materials required manual validation to ensure completeness, consistent file naming, and operational readiness. Inconsistent records and missing information could impact content retrieval, distribution, and scheduling processes.",
      approach: [
        "Reviewed and validated content metadata, including duration, production year, storage location, broadcast status, age rating, province, OPK, and CB information",
        "Performed quality checks on production materials to ensure completeness and compliance with internal standards",
        "Standardized file naming conventions to improve content organization and retrieval efficiency",
        "Managed content extraction and preparation from the Kumulate system for operational and distribution needs",
        "Maintained and updated content records to ensure data consistency across content libraries and operational databases",
      ],
      result: [
        "Improved metadata consistency and accuracy across thousands of content records",
        "Reduced the risk of missing information and file naming discrepancies in production materials",
        "Enhanced content discoverability and streamlined content management workflows",
        "Supported operational teams by ensuring content assets were properly organized and ready for distribution",
      ],
      toolsUsed: [
        "Microsoft Excel",
        "Kumulate",
        "Metadata Management",
        "Content Validation",
        "File Management",
        ],
      image: "/images/case-study-placeholder.svg",
    },
    {
      id: 2,
      title: "Network Infrastructure Design",
      category: "Networking",
      datasetInfo: "Enterprise Scale • Cisco • VLAN",
      problem: "Company network suffered frequent bottlenecks and security vulnerabilities due to a flat network topology with no segmentation between departments.",
      approach: [
        "Designed multi-layer VLAN segmentation per department",
        "Configured inter-VLAN routing using Layer 3 switches",
        "Implemented firewall rules and access control lists (ACL)",
        "Set up centralized monitoring with SNMP-based tools",
      ],
      result: [
        "Network performance improved by 40% due to traffic segmentation",
        "Security incidents reduced to zero within 6 months post-deployment",
        "Network uptime reached 99.8% SLA compliance",
      ],
      toolsUsed: ["Cisco Packet Tracer", "Wireshark", "VLAN", "ACL", "SNMP"],
      image: "/images/case-study-placeholder.svg",
    },
    {
      id: 3,
      title: "Inventory Management System",
      category: "Coding / Backend System",
      datasetInfo: "Full Stack • Node.js • REST API",
      problem: "A retail client managed inventory through paper logs and Excel files, leading to stock discrepancies, slow lookup times, and inability to scale.",
      approach: [
        "Designed RESTful API with Node.js + Express for CRUD operations",
        "Built role-based access control (RBAC) for admin and staff roles",
        "Integrated barcode scanner input via web interface",
        "Deployed with Docker and PostgreSQL on a VPS server",
      ],
      result: [
        "Stock lookup reduced from 15 minutes → under 5 seconds",
        "Inventory accuracy improved to 99.5% with automated tracking",
        "System handles 500+ simultaneous users without degradation",
      ],
      toolsUsed: ["Node.js", "Express", "PostgreSQL", "Docker", "JWT", "REST API"],
      image: "/images/case-study-placeholder.svg",
    },
    {
      id: 4,
      title: "Mobile App UI/UX Redesign",
      category: "UI/UX Design",
      datasetInfo: "Figma • User Research • 20 Participants",
      problem: "A mobile learning app had a 70% drop-off rate on the onboarding screen. User feedback indicated the UI was confusing and the navigation was unclear.",
      approach: [
        "Conducted user interviews and usability testing with 20 participants",
        "Identified 5 major pain points via journey mapping",
        "Redesigned onboarding flow from 8 steps → 3 steps",
        "Created high-fidelity prototypes in Figma with micro-animations",
      ],
      result: [
        "Onboarding completion rate increased from 30% → 82%",
        "User satisfaction score (SUS) improved from 58 → 84",
        "App store rating improved from 3.2 → 4.6 within 2 months",
      ],
      toolsUsed: ["Figma", "Maze", "FigJam", "Notion", "Loom"],
      image: "/images/case-study-placeholder.svg",
    },
    {
      id: 5,
      title: "Content Strategy & Production",
      category: "Content Creation",
      datasetInfo: "Multi-Platform • 3 Months Campaign",
      problem: "A government creative team lacked a systematic content production pipeline, resulting in inconsistent posting schedules and low engagement across platforms.",
      approach: [
        "Built a content calendar system in Notion for 3-month planning",
        "Produced short-form video content for TikTok and Instagram Reels",
        "Directed and edited podcast episodes for YouTube distribution",
        "Implemented analytics review cycles to iterate on top-performing content",
      ],
      result: [
        "Content output increased from 2 → 12 pieces per month",
        "Social media engagement grew by 3x within the first campaign month",
        "Podcast episode views exceeded 5K per episode on average",
      ],
      toolsUsed: ["CapCut", "Canva", "Notion", "Adobe Premiere", "YouTube Studio"],
      image: "/images/case-study-placeholder.svg",
    },
  ],

  socialLinks: {
    github: "https://github.com/alfathalifdewa",
    linkedin: "https://www.linkedin.com/in/alfathalif-dewa/",
    twitter: "https://x.com/needpancake",
    instagram: "https://www.instagram.com/alfathalifdewa/",
    tiktok: "https://www.tiktok.com/@needpancake",
  },
};
